// frontend/src/lib/components/ProjectForm.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import { X } from 'lucide-svelte';
	import type { ProjectCreate } from '$lib/types';

	export let initialData: ProjectCreate | null = null;
	export let isEdit = false;

	const dispatch = createEventDispatcher();

	let formData: ProjectCreate = initialData || {
		name: '',
		analystInitials: '',
		startDate: new Date().toISOString().split('T')[0],
		endDate: new Date().toISOString().split('T')[0],
		eventType: 'CVI'
	};

	let loading = false;
	let error = '';

	function handleSubmit() {
		error = '';

		if (!formData.name.trim()) {
			error = 'Project name is required';
			return;
		}
		if (!formData.analystInitials.trim()) {
			error = 'Analyst initials are required';
			return;
		}
		if (new Date(formData.endDate) < new Date(formData.startDate)) {
			error = 'End date must be after start date';
			return;
		}

		dispatch('submit', formData);
	}

	function handleCancel() {
		dispatch('cancel');
	}

	function handleOverlayClick(e: MouseEvent) {
		if (e.target === e.currentTarget) {
			handleCancel();
		}
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			handleCancel();
		}
	}
</script>

<svelte:window on:keydown={handleKeyDown} />

<!-- svelte-ignore a11y-click-events-have-key-events -->
<!-- svelte-ignore a11y-no-static-element-interactions -->
<div class="modal-overlay" on:click={handleOverlayClick} role="dialog" aria-modal="true">
	<!-- svelte-ignore a11y-click-events-have-key-events -->
	<!-- svelte-ignore a11y-no-static-element-interactions -->
	<div class="modal" on:click|stopPropagation>
		<div class="modal-header">
			<h2>{isEdit ? 'Edit Project' : 'Create New Project'}</h2>
			<button class="btn btn-outline btn-sm" on:click={handleCancel} style="padding: 0.25rem;">
				<X size={20} />
			</button>
		</div>

		<form on:submit|preventDefault={handleSubmit}>
			<div class="modal-body">
				{#if error}
					<div class="alert alert-error">
						{error}
					</div>
				{/if}

				<div class="form-group">
					<label class="form-label" for="name">Project Name *</label>
					<input
						type="text"
						id="name"
						class="form-control"
						bind:value={formData.name}
						required
						placeholder="Enter project name"
					/>
				</div>

				<div class="form-group">
					<label class="form-label" for="initials">Analyst Initials *</label>
					<input
						type="text"
						id="initials"
						class="form-control"
						bind:value={formData.analystInitials}
						required
						maxlength="10"
						placeholder="e.g., JD"
					/>
				</div>

				<div class="grid grid-cols-2">
					<div class="form-group">
						<label class="form-label" for="startDate">Start Date *</label>
						<input
							type="date"
							id="startDate"
							class="form-control"
							bind:value={formData.startDate}
							required
						/>
					</div>

					<div class="form-group">
						<label class="form-label" for="endDate">End Date *</label>
						<input
							type="date"
							id="endDate"
							class="form-control"
							bind:value={formData.endDate}
							required
						/>
					</div>
				</div>

				<div class="form-group">
					<label class="form-label" for="eventType">Event Type *</label>
					<select id="eventType" class="form-control" bind:value={formData.eventType} required>
						<option value="CVI">CVI - Cyber Vulnerability Investigation</option>
						<option value="CVPA">CVPA - Cyber Vulnerability Penetration Assessment</option>
					</select>
				</div>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-outline" on:click={handleCancel} disabled={loading}>
					Cancel
				</button>
				<button type="submit" class="btn btn-primary" disabled={loading}>
					{#if loading}
						<span class="loading" />
						Saving...
					{:else}
						{isEdit ? 'Update Project' : 'Create Project'}
					{/if}
				</button>
			</div>
		</form>
	</div>
</div>

// frontend/src/components/ProjectForm.tsx
import React, { useState } from 'react';
import { X } from 'lucide-react';
import type { ProjectCreate, EventType } from '../types';

interface ProjectFormProps {
  onSubmit: (project: ProjectCreate) => Promise<void>;
  onCancel: () => void;
  initialData?: ProjectCreate;
}

const ProjectForm: React.FC<ProjectFormProps> = ({ onSubmit, onCancel, initialData }) => {
  const [formData, setFormData] = useState<ProjectCreate>(
    initialData || {
      name: '',
      analystInitials: '',
      startDate: new Date().toISOString().split('T')[0],
      endDate: new Date().toISOString().split('T')[0],
      eventType: 'CVI',
    }
  );
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    setError('');
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    // Validation
    if (!formData.name.trim()) {
      setError('Project name is required');
      return;
    }
    if (!formData.analystInitials.trim()) {
      setError('Analyst initials are required');
      return;
    }
    if (new Date(formData.endDate) < new Date(formData.startDate)) {
      setError('End date must be after start date');
      return;
    }

    setLoading(true);
    try {
      await onSubmit(formData);
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to save project');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="modal-overlay" onClick={onCancel}>
      <div className="modal" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <h2>{initialData ? 'Edit Project' : 'Create New Project'}</h2>
          <button
            onClick={onCancel}
            className="btn btn-outline btn-sm"
            style={{ padding: '0.25rem' }}
          >
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="modal-body">
            {error && (
              <div className="alert alert-error">
                {error}
              </div>
            )}

            <div className="form-group">
              <label className="form-label">Project Name *</label>
              <input
                type="text"
                name="name"
                className="form-control"
                value={formData.name}
                onChange={handleChange}
                required
                placeholder="Enter project name"
              />
            </div>

            <div className="form-group">
              <label className="form-label">Analyst Initials *</label>
              <input
                type="text"
                name="analystInitials"
                className="form-control"
                value={formData.analystInitials}
                onChange={handleChange}
                required
                maxLength={10}
                placeholder="e.g., JD"
              />
            </div>

            <div className="grid grid-cols-2">
              <div className="form-group">
                <label className="form-label">Start Date *</label>
                <input
                  type="date"
                  name="startDate"
                  className="form-control"
                  value={formData.startDate}
                  onChange={handleChange}
                  required
                />
              </div>

              <div className="form-group">
                <label className="form-label">End Date *</label>
                <input
                  type="date"
                  name="endDate"
                  className="form-control"
                  value={formData.endDate}
                  onChange={handleChange}
                  required
                />
              </div>
            </div>

            <div className="form-group">
              <label className="form-label">Event Type *</label>
              <select
                name="eventType"
                className="form-control"
                value={formData.eventType}
                onChange={handleChange}
                required
              >
                <option value="CVI">CVI - Cyber Vulnerability Investigation</option>
                <option value="CVPA">CVPA - Cyber Vulnerability Penetration Assessment</option>
              </select>
            </div>
          </div>

          <div className="modal-footer">
            <button
              type="button"
              onClick={onCancel}
              className="btn btn-outline"
              disabled={loading}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={loading}
            >
              {loading ? (
                <>
                  <span className="loading" />
                  Saving...
                </>
              ) : (
                initialData ? 'Update Project' : 'Create Project'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ProjectForm;
